window.createCombatVisuals=({T,scene,mesh,mat})=>{
 function texture(kind){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d'),g=ctx.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,kind==='smoke'?'rgba(225,233,222,.7)':'rgba(255,205,128,1)');g.addColorStop(.35,kind==='smoke'?'rgba(205,219,213,.4)':'rgba(255,45,70,.9)');g.addColorStop(1,'rgba(90,0,30,0)');ctx.fillStyle=g;ctx.fillRect(0,0,128,128);if(kind==='soul'){ctx.fillStyle='#ffdcc3';ctx.beginPath();ctx.moveTo(64,15);ctx.bezierCurveTo(96,18,100,65,68,90);ctx.lineTo(48,117);ctx.lineTo(49,85);ctx.bezierCurveTo(20,50,32,19,64,15);ctx.fill();ctx.fillStyle='#321020';ctx.beginPath();ctx.moveTo(43,47);ctx.lineTo(61,53);ctx.lineTo(53,63);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(84,47);ctx.lineTo(67,54);ctx.lineTo(74,63);ctx.closePath();ctx.fill();ctx.fillRect(58,70,12,9)}return new T.CanvasTexture(c)}
 const soulTex=texture('soul'),smokeTex=texture('smoke');
 const souls=Array.from({length:20},()=>{const s=new T.Sprite(new T.SpriteMaterial({map:soulTex,color:'#f47382',transparent:true,depthWrite:false,toneMapped:false}));scene.add(s);s.visible=false;return s});
 const smokes=Array.from({length:24},()=>{const s=new T.Sprite(new T.SpriteMaterial({map:smokeTex,transparent:true,depthWrite:false}));scene.add(s);s.visible=false;return s});
 function ring(color,width){const r=mesh(new T.RingGeometry(1-width,1,96),new T.MeshBasicMaterial({color,transparent:true,opacity:.7,side:T.DoubleSide,depthWrite:false}),0,4,0);r.rotation.x=-Math.PI/2;r.castShadow=r.receiveShadow=false;r.visible=false;return r}
 const chargeRing=ring('#fd3c64',.055),blastRing=ring('#ff6952',.018),refreshRing=ring('#a5ff93',.08);
 const orbit=Array.from({length:12},()=>{const o=mesh(new T.OctahedronGeometry(2),new T.MeshBasicMaterial({color:'#adffb0'}));o.visible=false;return o});
 function ribbons(color,opacity){const positions=new Float32Array(20*6*3),geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(positions,3));const o=mesh(geo,new T.MeshBasicMaterial({color,transparent:true,opacity,side:T.DoubleSide,depthWrite:false,blending:T.AdditiveBlending}));o.frustumCulled=false;o.castShadow=o.receiveShadow=false;o.visible=false;return {o,positions,geo}}
 const outer=ribbons('#480b21',.8),inner=ribbons('#fd284b',.75);outer.o.material.blending=T.NormalBlending;inner.o.material.toneMapped=false;
 function drawTrails(buffer,waves,width){buffer.o.visible=waves.length>0;let n=0;for(const w of waves.slice(0,20)){const tip=w.distance,tail=Math.max(0,tip-105),sx=-w.dy*width,sz=w.dx*width,A=[w.x+w.dx*tail+sx,34,w.y+w.dy*tail+sz],B=[w.x+w.dx*tail-sx,34,w.y+w.dy*tail-sz],C=[w.x+w.dx*tip+sx*.5,43,w.y+w.dy*tip+sz*.5],D=[w.x+w.dx*tip-sx*.5,43,w.y+w.dy*tip-sz*.5];for(const v of [A,B,C,B,D,C])for(const c of v)buffer.positions[n++]=c}buffer.geo.setDrawRange(0,n/3);buffer.geo.attributes.position.needsUpdate=true}
 // The reference device is modeled as a solid red/silver handheld object.
 const device=new T.Group();scene.add(device);device.visible=false;const red=mat('#bb152d',.3),silver=mat('#d9dedc',.24),black=mat('#1c2222',.32),skin=mat('#dbad8d',.6);
 mesh(new T.BoxGeometry(8,14,6),red,0,0,0,device);mesh(new T.BoxGeometry(8.4,11,1),silver,0,-.5,3.1,device);mesh(new T.BoxGeometry(5.2,9,.7),red,0,-.5,3.8,device);mesh(new T.CylinderGeometry(3,3.8,5,16),silver,0,9.4,0,device);mesh(new T.CylinderGeometry(2.2,2.2,4,16),red,0,13.4,0,device);mesh(new T.BoxGeometry(2,3,.5),black,3.3,2,3.8,device);mesh(new T.SphereGeometry(3,12,8),skin,3,-2,2,device);
 let lastSmoke=null,smokeOrigin=new T.Vector3(),smokeForward=new T.Vector3();
 function mouth(hero,id){hero.updateMatrixWorld(true);return hero.localToWorld(new T.Vector3(5,id==='classic'||id==='miti'?55:id==='massa'?97:96,19))}
 function pose(hero,c){if(!c)return;const progress=1-c.remaining/c.duration;if(c.id==='requiem'){if(hero.userData.body)hero.userData.body.rotation.x=-.14*Math.sin(progress*Math.PI);for(const arm of hero.userData.arms||[]){arm.shoulder.rotation.z=arm.shoulder.position.x>0?-.65:.65;arm.shoulder.rotation.x=-.35;arm.elbow.rotation.x=-.4}hero.position.y+=Math.sin(progress*Math.PI)*7}else{if(hero.userData.arms?.[1]){hero.userData.arms[1].shoulder.rotation.x=-1.5;hero.userData.arms[1].elbow.rotation.x=-1.2}if(hero.userData.head)hero.userData.head.rotation.x=.08}}
 function animateAgent(g,a){for(const arm of g.userData.arms||[])arm.shoulder.rotation.z=0;if(a.attackWindup>0||a.attackSwing>0){const arm=g.userData.arms?.[1];if(arm){arm.shoulder.rotation.x=a.attackWindup>0?.8:-1.35;arm.elbow.rotation.x=a.attackWindup>0?-1.2:-.35}g.rotation.y=Math.atan2(a.targetX-a.x,a.targetY-a.y)}g.traverse(o=>{if(o.isMesh&&o.material.emissive){o.material.emissive.set(a.damageFlash>0?'#ff2424':'#000000');o.material.emissiveIntensity=a.damageFlash>0?.6:0}})}
 function render(data,hero){const c=data.combat;if(!c)return;const playing=data.state==='running'||data.state==='paused',cast=c.casting;pose(hero,cast);hero.traverse(o=>{if(o.isMesh&&o.material.emissive){o.material.emissive.set(c.damageFlash>0?'#ff3c30':c.healFlash>0?'#69dd5e':'#000000');o.material.emissiveIntensity=c.damageFlash>0?.5:c.healFlash>0?.28:0}});
  chargeRing.visible=playing&&cast?.id==='requiem';if(chargeRing.visible){const t=1-cast.remaining/cast.duration;chargeRing.position.set(data.p.x,4,data.p.y);chargeRing.scale.setScalar(65+Math.sin(t*Math.PI)*35);chargeRing.material.opacity=.3+t*.5}
  for(let i=0;i<20;i++){const s=souls[i],w=c.waves[i];s.visible=playing&& (!!w||cast?.id==='requiem');if(w){s.position.set(w.x+w.dx*w.distance,43+Math.sin(data.elapsed*13+i)*6,w.y+w.dy*w.distance);s.scale.set(30,40,1);s.material.opacity=1-w.distance/650}else if(cast?.id==='requiem'){const t=1-cast.remaining/cast.duration,a=i*Math.PI*2/20+t*4,rad=85*(1-t)+15;s.position.set(data.p.x+Math.sin(a)*rad,20+t*50+Math.sin(i*3+t*5)*8,data.p.y+Math.cos(a)*rad);s.scale.setScalar(17+t*10);s.material.opacity=.3+t*.65}}
  drawTrails(outer,playing?c.waves:[],9);drawTrails(inner,playing?c.waves:[],3.5);blastRing.visible=playing&&c.waves.length>0;if(blastRing.visible){const w=c.waves[0];blastRing.position.set(w.x,5,w.y);blastRing.scale.setScalar(Math.max(1,w.distance));blastRing.material.opacity=(1-w.distance/550)*.55}
  const inhaling=cast?.id==='aegis';device.visible=playing&&(inhaling||c.smoke?.age<1.2);if(device.visible){const pos=mouth(hero,data.skin);const t=inhaling?Math.min(1,(1-cast.remaining/cast.duration)*3):Math.max(0,1-(c.smoke.age-.25)*2);device.position.copy(pos);device.position.y-=18*(1-t);device.quaternion.copy(hero.quaternion);device.rotateX(-.18)}
  if(c.smoke&&c.smoke!==lastSmoke){lastSmoke=c.smoke;smokeOrigin.copy(mouth(hero,data.skin));smokeForward.set(0,0,1).applyQuaternion(hero.quaternion)}
  for(let i=0;i<smokes.length;i++){const s=smokes[i],age=c.smoke?.age||0;s.visible=playing&&!!c.smoke;if(s.visible){const f=i/24,a=i*2.4,r=(4+age*12)*f;s.position.copy(smokeOrigin).addScaledVector(smokeForward,8+age*24+f*8);s.position.x+=Math.sin(a)*r;s.position.z+=Math.cos(a)*r*.6;s.position.y+=age*18+Math.sin(a)*r*.3;s.scale.setScalar(10+age*13+f*9);s.material.opacity=.3*Math.pow(1-age/2.5,1.5)}}
  refreshRing.visible=playing&&c.refreshFlash>0;if(refreshRing.visible){const t=1-c.refreshFlash/.85;refreshRing.position.set(data.p.x,5,data.p.y);refreshRing.scale.setScalar(30+t*115);refreshRing.material.opacity=(1-t)*.8}orbit.forEach((o,i)=>{o.visible=refreshRing.visible;if(o.visible){const a=data.elapsed*6+i*Math.PI/6,t=1-c.refreshFlash/.85;o.position.set(data.p.x+Math.sin(a)*(35+t*60),20+Math.sin(i*4)*10+t*90,data.p.y+Math.cos(a)*(35+t*60));o.scale.setScalar(1+c.refreshFlash*2)}});
 }
 return {render,animateAgent};
};
