const $=id=>document.getElementById(id),canvas=$('game'),ctx=null;
let saved={coins:0,best:0,hook:false,speedCharges:0,invisCharges:0,shieldCharges:0};try{saved={...saved,...JSON.parse(localStorage.getItem('mellrun-v1')||'{}')}}catch{}
let state='menu',previous='menu',elapsed=0,stage=1,lap=1,levelTime=0,grace=3,spawnTimer=0,coinTimer=0,speed=0,invis=0,shield=0,cooldown=0,grapple=null,agents=[],coins=[],particles=[],keys={},camera={x:0,y:0},p={x:-480,y:460},last=0,sound=false,audio;
const hero=new Image(),chick=new Image();hero.src='assets/hero.png';chick.src='assets/chick.png';let heroSprite,chickSprite;
hero.onload=()=>{let c=document.createElement('canvas');c.width=48;c.height=48;let x=c.getContext('2d');x.drawImage(hero,125,25,350,340,0,0,48,48);heroSprite=c};
chick.onload=()=>{let c=document.createElement('canvas');c.width=32;c.height=40;let x=c.getContext('2d');x.drawImage(chick,0,0,32,40);let d=x.getImageData(0,0,32,40);for(let i=0;i<d.data.length;i+=4)if(d.data[i+1]>d.data[i]*1.4&&d.data[i+1]>d.data[i+2]*1.5)d.data[i+3]=0;x.putImageData(d,0,0);chickSprite=c};
let seed=431;function random(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}const trees=[];for(let i=0;i<155;i++){let x=random()*2300-1150,y=random()*2300-1150;if(Math.abs(x+y)<95||Math.abs(x-y)<100||Math.abs(x)>1040||Math.abs(y)>1040||Math.hypot(x+480,y-460)<130)continue;trees.push({x,y,r:19+random()*13,type:y<x?0:1})}
const towers=[{x:-750,y:730},{x:750,y:-730},{x:-850,y:-120},{x:850,y:120},{x:-250,y:250},{x:250,y:-250},{x:-900,y:600},{x:900,y:-600}];const anchors=[...trees,...towers];
function persist(){try{localStorage.setItem('mellrun-v1',JSON.stringify(saved))}catch{}}function beep(f=440){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.12)}catch{}}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',2400)}
function ui(){$('shieldStock').textContent='×'+saved.shieldCharges;$('shieldTimer').textContent=shield>0?Math.ceil(shield)+'с · АКТИВНО':'5 сек.';$('invisStock').textContent='×'+saved.invisCharges;$('speedStock').textContent='×'+saved.speedCharges;$('invisTimer').textContent=invis>0?Math.ceil(invis)+'с · АКТИВНО':'15 сек.';$('speedTimer').textContent=speed>0?Math.ceil(speed)+'с · АКТИВНО':'60 сек.';$('coins').textContent=saved.coins;$('best').textContent=String(saved.best).padStart(5,'0');$('score').textContent=String(Math.floor(elapsed*10)).padStart(5,'0');$('level').innerHTML=String(stage).padStart(2,'0')+' <small>/ 15</small>';$('lap').textContent=lap;$('bar').style.width=(levelTime/30*100)+'%';$('effects').textContent=[shield>0?'ЩИТ '+Math.ceil(shield)+'с':(saved.shieldCharges?'Q · ЩИТ ×'+saved.shieldCharges:''),speed>0?'ТУРБО '+Math.ceil(speed)+'с':(saved.speedCharges?'SHIFT · ТУРБО ×'+saved.speedCharges:''),invis>0?'НЕВИДИМОСТЬ '+Math.ceil(invis)+'с':(saved.invisCharges?'R · НЕВИДИМОСТЬ ×'+saved.invisCharges:''),saved.hook?(cooldown>0?'ХУК '+Math.ceil(cooldown)+'с':'ХУК ГОТОВ · ПРОБЕЛ'):''].filter(Boolean).join(' • ')}
function showMenu(title,text,playText){$('modalTitle').innerHTML=title;$('modalText').innerHTML=text;$('play').innerHTML=playText+' <span>↗</span>';$('overlay').classList.remove('hidden')}
function start(){elapsed=0;stage=1;lap=1;levelTime=0;grace=3;spawnTimer=0;coinTimer=0;agents=[];coins=[];particles=[];p={x:-480,y:460};camera={...p};grapple=null;cooldown=0;for(let i=0;i<22;i++)spawnCoin();state='running';$('overlay').classList.add('hidden');$('shop').classList.add('hidden');ui()}
function activate(type){if(state!=='running')return;const key=type+'Charges';if(!saved[key]){toast('Нет усиления в запасе — купи его в магазине');return}if(type==='invis'&&invis>0||type==='speed'&&speed>0||type==='shield'&&shield>0){toast('Усиление уже действует');return}saved[key]--;if(type==='invis')invis=15;else if(type==='shield')shield=5;else speed=60;persist();ui();beep(700);toast(type==='invis'?'Невидимость: 15 секунд':type==='shield'?'Щит: 5 секунд неуязвимости':'Ускорение: 60 секунд')}
function pause(){if(state==='running'){state='paused';keys={};showMenu('ПЕРЕВЕДИ<br><span>ДЫХАНИЕ.</span>','Погоня на паузе. Птенчик-маркет открыт.<br>Вернись, когда будешь готов.','ПРОДОЛЖИТЬ')}else if(state==='paused'){state='running';$('overlay').classList.add('hidden')}}
$('play').onclick=()=>state==='paused'?pause():start();$('pause').onclick=pause;$('restart').onclick=start;
function openShop(){previous=state;if(state==='running')state='paused';keys={};$('shopMsg').textContent='Баланс: '+saved.coins+' птенчиков';$('shop').classList.remove('hidden')}
$('shopOpen').onclick=openShop;$('footerShop').onclick=openShop;$('closeShop').onclick=()=>{$('shop').classList.add('hidden');state=previous;};
document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const type=b.dataset.buy,cost={speed:12,invis:18,hook:25,shield:6}[type];if(type==='hook'&&saved.hook){$('shopMsg').textContent='Хук уже куплен — используй пробел или нажми на объект.';return}if(saved.coins<cost){$('shopMsg').textContent='Не хватает '+(cost-saved.coins)+' птенчиков. Собирай их на карте!';return}saved.coins-=cost;if(type==='speed')saved.speedCharges++;if(type==='invis')saved.invisCharges++;if(type==='shield')saved.shieldCharges++;if(type==='hook')saved.hook=true;persist();ui();beep(880);$('shopMsg').textContent='Куплено в запас! R — невидимость, Shift — скорость, Q — щит. Баланс: '+saved.coins+' птенчиков.'});
$('sound').onclick=()=>{sound=!sound;$('sound').textContent='ЗВУК: '+(sound?'ВКЛ':'ВЫКЛ');beep()};
window.addEventListener('keydown',e=>{let k=e.key.toLowerCase();const map={'ц':'w','ф':'a','ы':'s','в':'d','у':'e','к':'r','й':'q'};k=map[k]||k;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='escape'){if(!$('shop').classList.contains('hidden'))$('closeShop').click();else pause()}if(k===' '&&!e.repeat)hook();if(k==='q'&&!e.repeat)activate('shield');if(k==='r'&&!e.repeat)activate('invis');if(k==='shift'&&!e.repeat)activate('speed');keys[k]=true});window.addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false;const m={'ц':'w','ф':'a','ы':'s','в':'d'};if(m[e.key.toLowerCase()])keys[m[e.key.toLowerCase()]]=false});window.addEventListener('blur',()=>{keys={};if(state==='running')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='running')pause()});
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false});$('touchHook').onclick=()=>hook();$('touchInvis').onclick=()=>activate('invis');$('touchSpeed').onclick=()=>activate('speed');$('shieldAbility').onclick=()=>activate('shield');$('touchShield').onclick=()=>activate('shield');$('invisAbility').onclick=()=>activate('invis');$('speedAbility').onclick=()=>activate('speed');
function free(x,y,r=13){return Math.abs(x)<1120&&Math.abs(y)<1120&&!trees.some(t=>Math.hypot(x-t.x,y-t.y)<t.r*.65+r)&&!towers.some(t=>Math.hypot(x-t.x,y-t.y)<r+23)}
function move(a,dx,dy,r=13){if(free(a.x+dx,a.y,r))a.x+=dx;if(free(a.x,a.y+dy,r))a.y+=dy}
function spawnCoin(){for(let n=0;n<100;n++){let x=random()*2100-1050,y=random()*2100-1050;if(free(x,y,20)){coins.push({x,y});return}}}
function spawnAgent(){for(let n=0;n<100;n++){let angle=random()*Math.PI*2,x=p.x+Math.cos(angle)*480,y=p.y+Math.sin(angle)*480;if(free(x,y)){agents.push({x,y,phase:random()*6});return}}}
function project(x,y,z=0){return window.project3D?window.project3D(x,y,z):{x:0,y:0}}
function hook(target){if(state!=='running')return;if(!saved.hook){toast('Купи хук в птенчик-маркете · 25 птенчиков');return}if(cooldown>0)return;let near=target||anchors.filter(t=>Math.hypot(t.x-p.x,t.y-p.y)>75&&Math.hypot(t.x-p.x,t.y-p.y)<440).sort((a,b)=>{let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);return Math.hypot(a.x-p.x-dx*220,a.y-p.y-dy*220)-Math.hypot(b.x-p.x-dx*220,b.y-p.y-dy*220)})[0];if(!near||Math.hypot(near.x-p.x,near.y-p.y)>440){toast('Нет цели в радиусе хука');return}let d=Math.hypot(near.x-p.x,near.y-p.y);grapple={x:near.x+(p.x-near.x)/d*65,y:near.y+(p.y-near.y)/d*65,target:near};cooldown=2.5;beep(250)}
canvas.onclick=e=>{if(state!=='running'||!saved.hook)return;let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;let t=anchors.map(t=>({t,s:project(t.x,t.y,35)})).sort((a,b)=>Math.hypot(a.s.x-x,a.s.y-y)-Math.hypot(b.s.x-x,b.s.y-y))[0];if(t&&Math.hypot(t.s.x-x,t.s.y-y)<55)hook(t.t)};
function update(dt){if(state!=='running')return;elapsed+=dt;levelTime+=dt;grace-=dt;shield=Math.max(0,shield-dt);speed=Math.max(0,speed-dt);invis=Math.max(0,invis-dt);cooldown=Math.max(0,cooldown-dt);if(levelTime>=30){levelTime-=30;stage++;if(stage>15){stage=1;lap++;agents=[]}grace=2;toast('УРОВЕНЬ '+stage+' · КРУГ '+lap);beep(650)}let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);let len=Math.hypot(dx,dy);if(grapple){let d=Math.hypot(grapple.x-p.x,grapple.y-p.y);if(d<12)grapple=null;else{let step=Math.min(d,750*dt);p.x+=(grapple.x-p.x)/d*step;p.y+=(grapple.y-p.y)/d*step;if(!free(p.x,p.y,9)&&d<80)grapple=null}}else if(len){let v=155*(speed>0?1.55:1);move(p,dx/len*v*dt,dy/len*v*dt)}spawnTimer+=dt;if(spawnTimer>Math.max(1.3,5-stage*.22)){spawnTimer=0;if(agents.length<3+stage+Math.min(lap-1,4))spawnAgent()}coinTimer+=dt;if(coinTimer>1.5&&coins.length<42){coinTimer=0;spawnCoin();let a=random()*6.28,x=p.x+Math.cos(a)*150,y=p.y+Math.sin(a)*150;if(free(x,y,20))coins.push({x,y})}for(let i=coins.length-1;i>=0;i--)if(Math.hypot(p.x-coins[i].x,p.y-coins[i].y)<35){coins.splice(i,1);saved.coins++;persist();beep(1000)}for(let a of agents){let vx=p.x-a.x,vy=p.y-a.y,d=Math.hypot(vx,vy);if(invis>0){vx=Math.cos(elapsed+a.phase);vy=Math.sin(elapsed+a.phase);d=1}let v=90+stage*3+Math.min(lap-1,4)*4;let ox=a.x,oy=a.y;move(a,vx/d*v*dt,vy/d*v*dt,10);if(Math.hypot(a.x-ox,a.y-oy)<v*dt*.2)move(a,-vy/d*v*dt,vx/d*v*dt,10);if(invis<=0&&shield<=0&&grace<=0&&!grapple&&Math.hypot(p.x-a.x,p.y-a.y)<27){state='caught';saved.best=Math.max(saved.best,Math.floor(elapsed*10));persist();showMenu('ТАЗИК<br><span>ОКРУЖИЛИ.</span>','Счёт: '+Math.floor(elapsed*10)+' · Уровень: '+stage+'<br>Птенчики и купленный хук сохранены. Попробуй ещё!','НОВЫЙ ПОБЕГ');beep(100);break}}camera.x+=(p.x-camera.x)*Math.min(1,dt*7);camera.y+=(p.y-camera.y)*Math.min(1,dt*7);ui()}
function resize(){if(window.resize3D)window.resize3D()}window.addEventListener('resize',resize);camera={...p};ui();function frame(t){let dt=Math.min(.04,(t-last)/1000||0);last=t;update(dt);window.render3D({p,trees,towers,agents,coins,state,elapsed,invis,speed,shield,grace,grapple,stage,lap},dt);requestAnimationFrame(frame)}requestAnimationFrame(frame);
