(()=>{
const T=THREE,canvas=document.getElementById('game'),renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,window.matchMedia("(pointer:coarse)").matches?1.25:1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new T.Scene();scene.background=new T.Color('#9cbdc0');scene.fog=new T.FogExp2('#9cbdc0',.00065);const cam=new T.PerspectiveCamera(48,1,1,3500);cam.position.set(-480,430,900);const hemi=new T.HemisphereLight('#d0ebff','#314623',2.2);scene.add(hemi);const sun=new T.DirectionalLight('#fff3d2',2.7);sun.position.set(-400,800,350);sun.castShadow=true;sun.shadow.mapSize.set(window.matchMedia("(pointer:coarse)").matches?1024:2048,window.matchMedia("(pointer:coarse)").matches?1024:2048);sun.shadow.camera.left=-700;sun.shadow.camera.right=700;sun.shadow.camera.top=700;sun.shadow.camera.bottom=-700;sun.shadow.camera.far=2000;sun.shadow.bias=-.001;scene.add(sun);scene.add(sun.target);
const mat=(color,roughness=.85)=>new T.MeshStandardMaterial({color,roughness});const grass=mat('#507840'),dark=mat('#414b3e'),bark=mat('#735540'),leaf=[mat('#345b2e'),mat('#507a38'),mat('#6b8d47')],direLeaf=[mat('#475046'),mat('#535c50'),mat('#687063')],stone=mat('#949786'),gold=mat('#d6ae5e'),water=new T.MeshStandardMaterial({color:'#3c919b',roughness:.22,metalness:.25}),skin=mat('#d9a682'),suit=mat('#263142'),white=mat('#eceddf'),black=mat('#151a20'),blue=mat('#009bd2',.25);
function mesh(geometry,material,x=0,y=0,z=0,parent=scene){const m=new T.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}function box(w,h,d,m,x,y,z,parent){return mesh(new T.BoxGeometry(w,h,d),m,x,y,z,parent)}function sphere(r,m,x,y,z,parent,sx=1,sy=1,sz=1){let o=mesh(new T.SphereGeometry(r,16,12),m,x,y,z,parent);o.scale.set(sx,sy,sz);return o}function cyl(rt,rb,h,m,x,y,z,parent){return mesh(new T.CylinderGeometry(rt,rb,h,16),m,x,y,z,parent)}
const ground=mesh(new T.PlaneGeometry(7000,7000,40,40),grass,0,-2,0);ground.rotation.x=-Math.PI/2;ground.castShadow=false;let dire=mesh(new T.PlaneGeometry(2400,1200),dark,420,-1,-420);dire.rotation.x=-Math.PI/2;dire.rotation.z=-Math.PI/4;
function trail(points,width,material,height=0){let curve=new T.CatmullRomCurve3(points.map(([x,z])=>new T.Vector3(x,height,z)));let samples=curve.getPoints(100),v=[],uv=[],indices=[];samples.forEach((p,i)=>{let next=samples[Math.min(i+1,100)],prev=samples[Math.max(i-1,0)],dir=new T.Vector3().subVectors(next,prev).normalize(),side=new T.Vector3(-dir.z,0,dir.x);for(let s of [-1,1]){let q=p.clone().addScaledVector(side,width/2*s);v.push(q.x,q.y,q.z);uv.push((s+1)/2,i/100)}if(i<100){let a=i*2;indices.push(a,a+1,a+2,a+1,a+3,a+2)}});let g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();let o=mesh(g,material);o.castShadow=false;return o}
trail([[-1230,1230],[-500,500],[0,0],[500,-500],[1230,-1230]],105,mat('#a49b75'),1);trail([[-1030,1030],[-1030,0],[-1030,-1030],[0,-1030],[1030,-1030]],105,mat('#a49b75'),1);trail([[-1030,1030],[0,1030],[1030,1030],[1030,0],[1030,-1030]],105,mat('#a49b75'),1);const river=trail([[-1250,-1250],[-600,-600],[0,0],[600,600],[1250,1250]],165,water,2);
// Stone ramps over the river keep all three lanes traversable.
for(let [x,z] of [[0,0],[-1030,-1030],[1030,1030]]){let b=box(145,6,180,stone,x,6,z);b.rotation.y=Math.PI/4;for(let n=-2;n<=2;n++){let line=box(140,1,2,mat('#687366'),x,10,z+n*24);line.rotation.y=Math.PI/4}}
// Impassable mountain perimeter: gameplay stops at ±1120, hidden inside the rock wall.
const mountainRock=mat('#697064'),mountainShade=mat('#555e55'),snow=mat('#c5cfc5');
function mountain(x,z,height,radius,angle){let g=new T.Group();g.position.set(x,0,z);g.rotation.y=angle;scene.add(g);let geo=new T.ConeGeometry(radius,height,9,5);let a=geo.attributes.position;for(let i=0;i<a.count;i++){let y=a.getY(i);if(y<height*.48){let jitter=Math.sin(i*13.7+x*.13+z*.21)*radius*.11;a.setX(i,a.getX(i)+jitter);a.setZ(i,a.getZ(i)+Math.cos(i*9.7)*radius*.08)}}geo.computeVertexNormals();mesh(geo,mountainRock,0,height/2-12,0,g);let b=mesh(new T.ConeGeometry(radius*.4,height*.35,7),mountainShade,radius*.5,height*.18,radius*.2,g);if(height>210)mesh(new T.ConeGeometry(radius*.18,height*.18,9),snow,0,height*.91-12,0,g);for(let n=0;n<3;n++)sphere(radius*.25,mountainShade,Math.sin(n*4)*radius*.5,20,Math.cos(n*4)*radius*.5,g,1.5,.8,1.2)}
for(let side=0;side<4;side++)for(let i=0;i<18;i++){let along=-1275+i*150,edge=1270+Math.sin(i*2.9+side)*35,h=180+Math.abs(Math.sin(i*8.1+side))*160;let x=side===0?-edge:side===1?edge:along,z=side===2?-edge:side===3?edge:along;mountain(x,z,h,170+Math.sin(i)*20,i*2.4);mountain(x*1.22,z*1.22,h*1.3,240,i)}
let terrainBuilt=false,heroGroup,activeSkin="classic",agentGroups=[],coinGroups=[];const loader=new T.TextureLoader();let birdFace=loader.load('assets/chick.png');birdFace.colorSpace=T.SRGBColorSpace;birdFace.repeat.set(.48,.32);birdFace.offset.set(.3,.63);const birdFaceMat=new T.MeshBasicMaterial({map:birdFace});
function tree(t){let g=new T.Group();g.position.set(t.x,0,t.y);scene.add(g);const dl=t.type?direLeaf:leaf;cyl(5,8,70,bark,0,35,0,g);for(let i=0;i<3;i++){let o=sphere(25-i*3,dl[i],(i%2?9:-6),55+i*17,0,g,1.3,1,1.1);o.rotation.y=t.x}if(t.type){let branch=cyl(2,4,38,bark,12,53,0,g);branch.rotation.z=-.8}let roots=cyl(9,17,9,bark,0,4,0,g)}
function tower(t){let g=new T.Group();g.position.set(t.x,0,t.y);scene.add(g);cyl(28,36,12,stone,0,6,0,g);cyl(17,23,64,stone,0,43,0,g);cyl(26,18,12,gold,0,79,0,g);sphere(14,t.x<0?mat('#95dfb4',.22):mat('#fa7954',.22),0,99,0,g,1,1.5,1);for(let i=0;i<4;i++){let a=i*Math.PI/2;box(10,19,10,stone,Math.cos(a)*22,89,Math.sin(a)*22,g)}}
function base(x,z,dire){const g=new T.Group();g.position.set(x,0,z);scene.add(g);cyl(80,100,12,stone,0,6,0,g);for(let i=0;i<5;i++){let a=i*6.28/5;let o=mesh(new T.ConeGeometry(20,90+i%2*20,6),dire?mat('#d7694b'):mat('#87d9b4'),Math.cos(a)*30,58,Math.sin(a)*30,g);o.rotation.z=Math.sin(a)*.2}let flag=box(3,130,3,bark,105,65,0,g);box(45,25,2,dire?mat('#ab3e29'):mat('#397958'),125,110,0,g)}base(-1010,1010,false);base(1010,-1010,true);
// Roshan caves, rune stones, outposts and neutral camps.
for(let [x,z] of [[-870,-730],[870,730]]){for(let i=0;i<6;i++){let a=i/6*Math.PI*1.8;let rock=sphere(38,mat('#62685d'),x+Math.cos(a)*57,28,z+Math.sin(a)*57,scene,1,1.3,1);rock.rotation.z=a}sphere(28,mat('#8c5747'),x,24,z,scene,1,1.2,1)}
for(let [x,z] of [[-450,-360],[450,360],[-800,380],[800,-380]]){cyl(22,28,7,stone,x,5,z);let r=mesh(new T.OctahedronGeometry(14),gold,x,27,z);r.rotation.z=.4;let light=new T.PointLight('#f8db7d',20,130);light.position.set(x,40,z);scene.add(light)}
function agent(){return window.createRunnerAgent({T,scene,mesh,mat})}
function createHero(id){return window.createGameSkin({T,scene,mesh,mat,id})}heroGroup=createHero('classic');

function coin(){let g=new T.Group();scene.add(g);sphere(10,mat('#f0db9d'),0,13,0,g,1.1,1.25,.9);sphere(7,mat('#f5e5b9'),0,25,3,g);let f=mesh(new T.PlaneGeometry(12,12),birdFaceMat,0,26,9,g);sphere(6,mat('#d9c48f'),-8,15,0,g,.5,1,1);sphere(6,mat('#d9c48f'),8,15,0,g,.5,1,1);cyl(1,1,8,gold,-4,4,1,g);cyl(1,1,8,gold,4,4,1,g);let ring=mesh(new T.RingGeometry(13,15,32),new T.MeshBasicMaterial({color:'#ffe68c',side:T.DoubleSide,transparent:true,opacity:.5}),0,.8,0,g);ring.rotation.x=-Math.PI/2;return g}
const shieldBubble=mesh(new T.SphereGeometry(43,32,24),new T.MeshBasicMaterial({color:'#72ceff',transparent:true,opacity:.18,side:T.DoubleSide,depthWrite:false}),0,45,0);shieldBubble.scale.set(1,1.3,1);shieldBubble.visible=false;const shieldRing=mesh(new T.TorusGeometry(40,1.1,8,64),new T.MeshBasicMaterial({color:'#bcefff',transparent:true,opacity:.7}),0,45,0);shieldRing.visible=false;
// Rain uses one draw call; puddles share the same positions as movement physics.
const rainCount=230,rainPositions=new Float32Array(rainCount*6),rainGeometry=new T.BufferGeometry();rainGeometry.setAttribute('position',new T.BufferAttribute(rainPositions,3));const rain=new T.LineSegments(rainGeometry,new T.LineBasicMaterial({color:'#bbd9e4',transparent:true,opacity:0,depthWrite:false}));rain.frustumCulled=false;scene.add(rain);
const puddleMaterial=new T.MeshPhysicalMaterial({color:'#658d99',roughness:.09,metalness:.38,transparent:true,opacity:0,depthWrite:false,clearcoat:1});const puddleGroups=window.PUDDLES.map(p=>{let g=mesh(new T.CircleGeometry(1,48),puddleMaterial,p.x,3.2,p.y);g.rotation.x=-Math.PI/2;g.scale.set(p.rx,p.ry,1);g.castShadow=false;g.visible=false;return g});
const hookGroup=new T.Group();scene.add(hookGroup);const metal=new T.MeshStandardMaterial({color:'#a8adb0',metalness:.85,roughness:.32});const hookPath=new T.CatmullRomCurve3([[0,7,0],[0,-4,0],[1,-13,0],[7,-19,0],[16,-18,0],[21,-11,0],[20,-4,0],[17,1,0]].map(p=>new T.Vector3(...p)));mesh(new T.TubeGeometry(hookPath,40,2.1,10,false),metal,0,0,0,hookGroup);let hookTip=mesh(new T.ConeGeometry(2.3,8,12),metal,16,4,0,hookGroup);hookTip.rotation.z=.38;let hookEye=mesh(new T.TorusGeometry(3.1,1.2,8,16),metal,0,9,0,hookGroup);
const chain=new T.InstancedMesh(new T.TorusGeometry(2.8,.85,6,12),metal,180);chain.instanceMatrix.setUsage(T.DynamicDrawUsage);chain.frustumCulled=false;scene.add(chain);const link=new T.Object3D(),up=new T.Vector3(0,1,0);let oldPosition=new T.Vector3(-480,0,460),heading=0;
window.resize3D=()=>{let w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);cam.aspect=w/h;cam.updateProjectionMatrix()};window.resize3D();window.project3D=(x,y,z)=>{let v=new T.Vector3(x,z,y).project(cam);return{x:(v.x+1)*canvas.width/2,y:(1-v.y)*canvas.height/2}};
window.render3D=(data,dt)=>{
 if(!terrainBuilt){data.trees.forEach(tree);data.towers.forEach(tower);terrainBuilt=true}
 if(activeSkin!==data.skin){scene.remove(heroGroup);heroGroup.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.map?.dispose();o.material.dispose()}});activeSkin=data.skin;heroGroup=createHero(activeSkin);heroGroup.rotation.y=heading;}
 heroGroup.position.set(data.p.x,0,data.p.y);const displacement=new T.Vector3().subVectors(heroGroup.position,oldPosition),moving=displacement.length()>.05;
 if(moving){heading=Math.atan2(displacement.x,displacement.z);heroGroup.rotation.y+=Math.atan2(Math.sin(heading-heroGroup.rotation.y),Math.cos(heading-heroGroup.rotation.y))*Math.min(1,dt*12)}oldPosition.copy(heroGroup.position);
 if(data.state==='running'||data.state==='menu')heroGroup.userData.moving=moving;window.animateCharacter(heroGroup,data.elapsed,heroGroup.userData.moving);heroGroup.traverse(o=>{if(o.isMesh){if(o.userData.baseOpacity===undefined)o.userData.baseOpacity=o.material.opacity;o.material.transparent=data.invis>0||o.userData.baseOpacity<1;o.material.opacity=o.userData.baseOpacity*(data.invis>0?.28:1)}});
 while(agentGroups.length<data.agents.length)agentGroups.push(agent());agentGroups.forEach((g,i)=>{const a=data.agents[i];g.visible=!!a;if(!a)return;const previous=g.userData.previous||{x:a.x,y:a.y},dx=a.x-previous.x,dz=a.y-previous.y,walking=Math.hypot(dx,dz)>.04;g.position.set(a.x,0,a.y);if(walking){const angle=Math.atan2(dx,dz);g.rotation.y+=Math.atan2(Math.sin(angle-g.rotation.y),Math.cos(angle-g.rotation.y))*Math.min(1,dt*12)}g.userData.previous={x:a.x,y:a.y};if(data.state==='running')g.userData.moving=walking;window.animateCharacter(g,data.elapsed+a.phase,g.userData.moving)});
 while(coinGroups.length<data.coins.length)coinGroups.push(coin());coinGroups.forEach((g,i)=>{const c=data.coins[i];g.visible=!!c;if(c){g.position.set(c.x,Math.sin(data.elapsed*3+i)*2,c.y);g.rotation.y=Math.sin(data.elapsed+i)*.2}});
 shieldBubble.visible=shieldRing.visible=data.shield>0;shieldBubble.position.set(data.p.x,45,data.p.y);shieldRing.position.set(data.p.x,45,data.p.y);shieldRing.rotation.y=data.elapsed;shieldBubble.material.opacity=.13+Math.sin(data.elapsed*5)*.035;
 const weather=data.weather,sky=new T.Color('#9cbdc0').lerp(new T.Color('#bfd5cc'),weather.sun*.4).lerp(new T.Color('#879e9f'),weather.rain*.7).lerp(new T.Color('#b2c1bb'),weather.fog*.6);scene.background.copy(sky);scene.fog.color.copy(sky);scene.fog.density=.00065+weather.fog*.0008+weather.rain*.00012;sun.intensity=1.7+weather.sun*2.1-weather.rain*.7;hemi.intensity=2.05-weather.rain*.3;sun.color.set(weather.sun>.55?'#ffe7a5':'#fff3d2');puddleMaterial.opacity=weather.wet*.42;puddleGroups.forEach(g=>g.visible=weather.wet>.01);
 rain.visible=weather.rain>.01;rain.material.opacity=weather.rain*.5;rain.position.set(data.p.x,0,data.p.y);if(rain.visible){for(let i=0;i<rainCount;i++){const x=Math.sin(i*127.13)*690,z=Math.cos(i*71.79)*690,y=((i*73.17-data.elapsed*460)%620+620)%620,offset=i*6;rainPositions[offset]=x;rainPositions[offset+1]=y;rainPositions[offset+2]=z;rainPositions[offset+3]=x-3;rainPositions[offset+4]=y+22;rainPositions[offset+5]=z+2;}rainGeometry.attributes.position.needsUpdate=true;}
 const target=new T.Vector3(data.p.x,460,data.p.y+550);cam.position.lerp(target,Math.min(1,dt*5));cam.lookAt(data.p.x,28,data.p.y-70);sun.position.set(data.p.x-350,750,data.p.y+250);sun.target.position.set(data.p.x,0,data.p.y);sun.target.updateMatrixWorld();
 hookGroup.visible=chain.visible=!!data.grapple;if(data.grapple){const tip=data.grapple.tip,start=new T.Vector3(data.p.x,39,data.p.y),finish=new T.Vector3(tip.x,65,tip.y),direction=finish.clone().sub(start),length=direction.length();direction.normalize();hookGroup.position.copy(finish);hookGroup.rotation.y=Math.atan2(direction.x,direction.z);hookGroup.rotation.z=data.grapple.phase==='pull'?.1:-.35;chain.count=Math.min(180,Math.ceil(length/5.3));for(let i=0;i<chain.count;i++){const t=(i+.5)/chain.count;link.position.copy(start).lerp(finish,t);link.position.y-=Math.sin(t*Math.PI)*Math.min(12,length*.04);link.quaternion.setFromUnitVectors(up,direction);if(i%2)link.rotateY(Math.PI/2);link.updateMatrix();chain.setMatrixAt(i,link.matrix)}chain.instanceMatrix.needsUpdate=true;}
 river.material.color.setHSL(.52,.35,.38+Math.sin(data.elapsed)*.015);renderer.render(scene,cam);
};
})();
