window.createSoundEffects=({volume=1,pickupElement,requiemElement})=>{
 let context,master,allowed=false,noise;
 function unlock(){allowed=true;const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;context??=new Audio();if(!master){master=context.createGain();master.gain.value=volume;master.connect(context.destination);noise=context.createBuffer(1,Math.floor(context.sampleRate*.12),context.sampleRate);const values=noise.getChannelData(0);for(let i=0;i<values.length;i++)values[i]=(Math.random()*2-1)*Math.exp(-i/values.length*3)}if(context.state==='suspended'&&!document.hidden)context.resume().catch(()=>{})}
 function tone(frequency,end,duration,gain,delay=0,type='sine'){if(!context||!allowed||volume<=0||document.hidden)return;const t=context.currentTime+delay,osc=context.createOscillator(),envelope=context.createGain();osc.type=type;osc.frequency.setValueAtTime(frequency,t);osc.frequency.exponentialRampToValueAtTime(end,t+duration);envelope.gain.setValueAtTime(0,t);envelope.gain.linearRampToValueAtTime(gain,t+.008);envelope.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(envelope);envelope.connect(master);osc.start(t);osc.stop(t+duration+.01);osc.onended=()=>{osc.disconnect();envelope.disconnect()}}
 function menu(){unlock();tone(540,760,.075,.018)}
 function purchase(){unlock();tone(1470,1280,.16,.022,0,'triangle');tone(2010,1700,.15,.017,.055,'sine');tone(2460,2100,.12,.011,.1,'triangle')}
 function step(){if(!context||!allowed||volume<=0||document.hidden)return;const t=context.currentTime,source=context.createBufferSource(),filter=context.createBiquadFilter(),gain=context.createGain();source.buffer=noise;source.playbackRate.value=.8+Math.random()*.3;filter.type='lowpass';filter.frequency.value=640;gain.gain.setValueAtTime(.033,t);gain.gain.exponentialRampToValueAtTime(.0001,t+.085);source.connect(filter);filter.connect(gain);gain.connect(master);source.start(t);source.stop(t+.1);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect()}}
 function pickup(){if(!allowed||volume<=0||document.hidden||!pickupElement?.getAttribute('src')||pickupElement.paused===false&&pickupElement.currentTime<.08)return;pickupElement.volume=volume*.14;pickupElement.currentTime=0;pickupElement.play().catch(()=>{})}
 function requiem(){unlock();if(volume<=0||document.hidden||!requiemElement?.getAttribute('src'))return;requiemElement.volume=volume*.24;requiemElement.currentTime=0;requiemElement.play().catch(()=>{})}
 const api={unlock,menu,purchase,step,pickup,requiem,setVolume(value){volume=Math.max(0,Math.min(1,Number(value)||0));if(master)master.gain.value=volume;for(const [element,level] of [[pickupElement,.14],[requiemElement,.24]])if(element){element.volume=volume*level;if(volume===0)element.pause()}},get volume(){return volume}};
 document.addEventListener('pointerdown',unlock);document.addEventListener('keydown',unlock);document.addEventListener('visibilitychange',()=>{if(document.hidden){context?.suspend().catch(()=>{});pickupElement?.pause();requiemElement?.pause()}else if(allowed&&context)context.resume().catch(()=>{})});
 return api;
};
